version: "3.7"

services:

  postgres:
    container_name: 'simple-messenger-postgres'
    image: 'postgres:11.2'
    restart: always
    ports:
      - '5434:5432'
    environment:
      - 'POSTGRES_USER=username'
      - 'POSTGRES_DB=simple-messenger'
      - 'POSTGRES_PASSWORD=password'