version: "3.7"

services:

  postgres:
    container_name: 'simple-messenger-postgres'
    image: 'postgres:11.2'
    restart: always
    ports:
      - '5434:5432'
    environment:
      - 'POSTGRES_USER=username'
      - 'POSTGRES_DB=simple-messenger'
      - 'POSTGRES_PASSWORD=password'

  postgres-test:
    container_name: 'simple-messenger-postgres-test'
    image: 'postgres:11.2'
    restart: always
    ports:
      - '5435:5432'
    environment:
      - 'POSTGRES_USER=username'
      - 'POSTGRES_DB=simple-messenger-test'
      - 'POSTGRES_PASSWORD=password'


  maildev:
    image: maildev/maildev
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "8080:1080"
      - "8025:1025"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"